// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5HQc-K8ZEjQJh84JTdWpuo90ASTKqP2w',
    appId: '1:353314204506:web:3ef94a3649e14b9509e163',
    messagingSenderId: '353314204506',
    projectId: 'pfe1-4c9de',
    authDomain: 'pfe1-4c9de.firebaseapp.com',
    storageBucket: 'pfe1-4c9de.appspot.com',
    measurementId: 'G-RBFXVBQL98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeeyHma5mrIs84DWa6eF793fX0e7ug9U',
    appId: '1:353314204506:android:ad6f43af87df134a09e163',
    messagingSenderId: '353314204506',
    projectId: 'pfe1-4c9de',
    storageBucket: 'pfe1-4c9de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQohn83KJ23vSgNtFCGOqY0SmqNiFPlew',
    appId: '1:353314204506:ios:47157ffd28d1527909e163',
    messagingSenderId: '353314204506',
    projectId: 'pfe1-4c9de',
    storageBucket: 'pfe1-4c9de.appspot.com',
    iosBundleId: 'com.example.rimTourisme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQohn83KJ23vSgNtFCGOqY0SmqNiFPlew',
    appId: '1:353314204506:ios:47157ffd28d1527909e163',
    messagingSenderId: '353314204506',
    projectId: 'pfe1-4c9de',
    storageBucket: 'pfe1-4c9de.appspot.com',
    iosBundleId: 'com.example.rimTourisme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5HQc-K8ZEjQJh84JTdWpuo90ASTKqP2w',
    appId: '1:353314204506:web:6ceb4682636ddb2209e163',
    messagingSenderId: '353314204506',
    projectId: 'pfe1-4c9de',
    authDomain: 'pfe1-4c9de.firebaseapp.com',
    storageBucket: 'pfe1-4c9de.appspot.com',
    measurementId: 'G-VPXCFPZG6N',
  );
}
